[package]
name = "grilme99/react-flipper"
version = "2.1.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "src"]

[dependencies]
React = "core-packages/react@17.0.1-rc.16"
Roact = "core-packages/roact-compat@17.0.1-rc.16.1"
Flipper = "reselim/flipper@2.0.0"
